# Production environment specific variables
env_name: production
domain_suffix: zhu-clan.emerj.net

# Domains
frontend_domain: "{{ domain_suffix }}"
backend_domain: "api.{{ domain_suffix }}"

# Git branches
frontend_branch: main
backend_branch: main

# Debug settings
node_env: production
debug: false

# CloudWatch log groups
cloudwatch_log_group_frontend: "/ec2/prod/{{ project_name }}/frontend"
cloudwatch_log_group_backend: "/ec2/prod/{{ project_name }}/backend"
cloudwatch_log_group_nginx: "/ec2/prod/{{ project_name }}/nginx"

# PM2 ecosystem file name
pm2_ecosystem_name: "ecosystem.production.config.js"
